services:
  - type: web
    name: resq-ai-server
    env: node
    rootDir: server
    buildCommand: cd server && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: resq-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: resq-server
          type: web
          property: url 