name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install client dependencies
      run: npm install --prefix client
    
    - name: Install server dependencies
      run: npm install --prefix server
    
    - name: Lint client
      run: npm run lint --prefix client || true
    
    - name: Lint server
      run: npm run lint --prefix server || true
    
    - name: Build client
      run: npm run build --prefix client
    
    - name: Build server
      run: npm run build --prefix server
    
    # Uncomment when tests are added
    # - name: Run client tests
    #   run: npm test --prefix client
    
    # - name: Run server tests
    #   run: npm test --prefix server 